version: "3"
services:
  web:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis
    ports:
      - "4000:4000"
  redis:
    image: redis:5
    expose:
      - "6379"
